### ISSUE TITLE
.env?

### ISSUE THREAD

**Issue by My-Inq** [bramses/gpt3-playground-notion#1]
"Add your Notion Keys and Notion Database ID to .env"

What is .env?

**Comment by My-Inq** [comment]
And what are Notion Keys?

**Comment by bramses** [comment]
Hi @My-Inq,

> What is .env?

`.env` is a npm package that keeps your API keys local and private: https://www.npmjs.com/package/dotenv

> And what are Notion Keys?

Notion keys are the API keys given by Notion: https://developers.notion.com/docs/getting-started#step-1-create-an-integration
